### ISSUE TITLE
precompile fails with ruby 2.7

### ISSUE THREAD

**Issue by bwlang** [QueueClassic/queue_classic#327]
I see this error when i run 
bundle exec rake assets:precompile

it works fine with 2.6.5

```
bundle exec rake assets:precompile
rake aborted!
NoMethodError: undefined method `map' for :needs:Symbol
Did you mean?  tap
/Users/langhorst/src/depletion-design/Rakefile:8:in `<top (required)>'
/Users/langhorst/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/langhorst/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
(base) langhorst@M-BLanghorst depletion-design % bundle exec rake assets:precompile --trace
rake aborted!
NoMethodError: undefined method `map' for :needs:Symbol
Did you mean?  tap
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:349:in `set_arg_names'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task_manager.rb:35:in `define_task'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:417:in `define_task'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/dsl_definition.rb:60:in `task'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/queue_classic-0.3.2/lib/queue_classic/tasks.rb:25:in `block in <main>'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task_manager.rb:232:in `in_namespace'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/dsl_definition.rb:141:in `namespace'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/queue_classic-0.3.2/lib/queue_classic/tasks.rb:9:in `<main>'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/Users/langhorst/src/depletion-design/Rakefile:8:in `<top (required)>'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/langhorst/.rbenv/versions/2.7.1/bin/rake:23:in `load'
/Users/langhorst/.rbenv/versions/2.7.1/bin/rake:23:in `<top (required)>'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/langhorst/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/Users/langhorst/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/langhorst/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

**Comment by bwlang** [comment]
This was not a 2.7.1 version issue... it was a public gem issue.
Accidentally changed both at once.
Switching to 
```
gem 'queue_classic', github: 'QueueClassic/queue_classic', branch: 'master'
```
works fine.
